### ISSUE TITLE
View rule exemption seems to be skipped over

### ISSUE THREAD

**Issue by mathcoder3141** [looker-open-source/look-at-me-sideways#101]
When running `lams` from the command line, I'm getting a K1 error thrown on `seat_status` but I have it declared as exempted. This is happening as well on our CI check. A snippet of the view file code is below:

```
view: seat_status {
  derived_table: {


    datagroup_trigger: default
    distribution: "subscription_start_month"
    sortkeys: ["subscription_start_month"]


    # LAMS
    # rule_exemptions: {
    #  K1: "DT being reworked so ignoring the LAMs error for now."
    # }
    sql: ...
```

I fiddled around with the view locally and applied the appropriate naming convention, hid the key, etc and that all worked so I suspect the exemption is being skipped over. Does the order of where things exist apply i.e., exemptions before sortkeys and distribution keys are declared?

**Comment by fabio-looker** [comment]
Hi @mathcoder3141 

Just from glancing at the above snippet, it seems like the exemption is being declared within the `derived_table` block, and not within the `view` block. Although there is normally only one derived_table block in a view, for generality exemptions are only inherited down, and do not affect ancestor blocks, so anything declared inside the derived_table would not exempt the view.

If it's not that, I'm not immediately sure what else it would be, as this seems to match one of the tests almost 100%: https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/17-local-exemptions/k1/test.view.lkml

That said, I'm leaning pretty heavily towards the placement of the exemption. I'll mark this as closed for now, but feel free to comment and I will re-open if the above tip doesn't get you unblocked.

Fabio

**Comment by mathcoder3141** [comment]
hey @fabio-looker, thank you for pointing that out. I fixed that and it did work.

Just as an FYI, the README also refers to a similar placement to what I had in the snipped.

https://github.com/looker-open-source/look-at-me-sideways#rule-exemptions

**Comment by fabio-looker** [comment]
That is a "T" rule which is concerned with the `sql`, whereas `K` rules are about the dimensions... but the point stands that I could choose a better exemption example! Thanks!
