### ISSUE TITLE
issues.md file doesn't create at github actions

### ISSUE THREAD

**Issue by barak-loc** [looker-open-source/look-at-me-sideways#104]
Should I Add another argument to the LAMS call?

<img width="308" alt="image" src="https://user-images.githubusercontent.com/92298725/187937677-fb261c75-648f-431c-b4f7-b07ee68567ef.png">

**Comment by fabio-looker** [comment]
Hi @barak-loc 

If you're using LAMS v2, the markdown is no longer the default output mode. Instead, by default errors are output in a human readable to the command line, which you can view by just clicking the ">" expand icon in that screenshot.

(If you do want the old markdown behavior, you can use the `--output=...` argument, and include `markdown` as a value in that list. You may have to adapt the rest of your Github action code similarly to the old v1 examples)

I'll mark this as closed, but feel free to respond if you still have any doubts or questions and I will review & respond!

**Comment by barak-loc** [comment]
works, thank you
