### ISSUE TITLE
PK regex is outdated in E2 rule

### ISSUE THREAD

**Issue by Kabulan0lak** [looker-open-source/look-at-me-sideways#106]
The E2 rule's regex used to check whether a field is a PK seems outdated:
`const pkRegex = /^([0-9]+pk|pk[0-9]+)_([a-z0-9A-Z_]+)$/;`

This forces all fields in `sql_on` to have a number following or preceding `pk`. But as I understand, an update made possible to use `pk_xxx` directly when the number of fields used for the PK is exactly 1.

The correct regex should then probably be the same as for rule K1-2-3-4:
`const pkRegex = /^([0-9]+pk|pk[0-9]*)_([a-z0-9A-Z_]+)$/`

I would gladly contribute to the project for others bugs I found, do not hesitate to contact me if needed: taha.belkhayate@jellysmack.com

**Comment by fabio-looker** [comment]
Thank you! I should be able to release an update for this in a day or two

**Comment by fabio-looker** [comment]
Fixed in v2.1.5
