### ISSUE TITLE
How to write a custom rule that detects the existence of a primary key?

### ISSUE THREAD

**Issue by markus-zhang-unity** [looker-open-source/look-at-me-sideways#108]
Hi experts, judging from [this quote](https://github.com/looker-open-source/look-at-me-sideways/issues/67#issuecomment-1049161451), rule K1 is limited to dimensions that begins with `pk(n)_`. Here is what I'd like to achieve:

In our project we do not force developers to follow any rule for naming the primary key field. However we still want to detect whether a primary key field has been defined. Here is an example:

```
view: instance_bill {
  sql_table_name: `my_project.reporting.instance_bill`
    ;;

  dimension: primary_key {
    primary_key: yes
    hidden: yes
    sql: concat(${TABLE}.Region,${TABLE}.NickName,${TABLE}.Tag) ;;
  }
  # rest of the view
```

My idea is to write a custom rule that detects whether there is a dimension that has a `yes` value for the `primary_key` field. How can I achieve that? I read the doc about custom rules but couldn't really get it.

Thanks in advance!

**Comment by fabio-looker** [comment]
Hi @markus-zhang-unity - I'm sorry I missed the tickets you opened back in November and only saw them now on a periodic review of open issues :(

If you are still interested in this, the exact use case you are interested in is set up as one of our tests:

https://github.com/looker-open-source/look-at-me-sideways/tree/master/__tests__/dummy-projects/08-object-iteration-rules

**Comment by afaiz-das42** [comment]
Hey @fabio-looker ! I'm trying to implement this exact rule that checks for a dimension with 'primary_key: yes' in each view. I have tried adding [this](https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/08-object-iteration-rules/manifest.lkml) code that you linked above, but I run into this error when the linter runs: 'Cannot convert undefined or null to object'. Do you know how I would be able to fix this?
