### ISSUE TITLE
Field Only Views Dont Work With Primary Keys?

### ISSUE THREAD

**Issue by mdp1125** [looker-open-source/look-at-me-sideways#110]
Hey @fabio-looker , I was hoping to get your thoughts on this..

We have an explore with a field-only view joined on to it to respect rule F1. It was working great. However now we are joining in a new view with a many_to_many relationship and when trying to use a field from the field-only view, Looker is asking for a primary_key in the field_only view...but that doesnt make sense given there is no true base view for it.

Any known workarounds for something like this?

**Comment by fabio-looker** [comment]
Hey @mdp1125 :wave: 

Without seeing the explore as a whole, I would already be a little cautious any time a many_to_many relationship crops up. In most cases, these correlate with inefficient join patterns and Looker's solution of applying symmetric aggregates can force _some_ measures to still work correctly, but the performance will likely be poor, and some measures would not work correctly.

That said, if you are sure the many_to_many is the only option, you can still declare a hidden dimension with primary_key inside of a field-only view, it would just reference the primary key from another view/table in the `sql` field, possibly creating a composite key from two views/tables if necessary for this view. Looker will use this SQL expression when constructing its symmetric aggregate expressions.

**Comment by mdp1125** [comment]
hey @fabio-looker thanks so much for the quick reply! I looked in to the underlying data and I agree, it is a bad idea to put it in to Looker at this stage. I may try your suggestion regarding composite keys but I do believe we need to rethink some of the data model and push parts of it to aggregate tables upstream. 

Thanks again, will close this out now.
