### ISSUE TITLE
Clarification re: ability to use style guide rules that are not automatically enforced

### ISSUE THREAD

**Issue by tkovich** [looker-open-source/look-at-me-sideways#114]
Hi Fabio! 

Teresa from DAS42 here -- I'm working on implementing LAMS for a client and wanted to clarify something.

I note this callout in the README:
`The linter can be configured to enforce rules from the style guide for all commits to your master branch.
`

It also specifies:
`The linter currently enforces rules K1-4, F1-4, E1-2, and T1-10 from the [style guide](https://looker-open-source.github.io/look-at-me-sideways/rules.html).
`

Based on these two notes, we're not clear whether there is or is not a way to use LAMS to implement one of the style guide rules that is NOT in the enforcement list, ex. T12 or T14 (aside from trying to create my own custom rule to enforce it). My gut says no, since I don't see them in the [rules](https://github.com/looker-open-source/look-at-me-sideways/tree/master/rules) subdirectory, but I thought I'd double check.

Thanks much!

Teresa Kovich
Principal Consultant, DAS42

**Comment by fabio-looker** [comment]
Hi Teresa,

Sorry, I initially missed the notification for this issue! You're right, the ones listed are the only ones provided. The style guide was written well before I even thought of making a linter for it, and when we worked on the linter, we only did a subset of the rules. If you have a suggestion on how the language could be clearer, feel free to let me know.

Fabio

**Comment by tkovich** [comment]
No worries! Thanks for the reply :) I think just to make it more explicit, I'd suggest instead of this:

The linter currently enforces rules K1-4, F1-4, E1-2, and T1-10 from the [style guide](https://looker-open-source.github.io/look-at-me-sideways/rules.html).

... you say something like:
The linter enforces rules K1-4, F1-4, E1-2, and T1-10 from the [style guide](https://looker-open-source.github.io/look-at-me-sideways/rules.html); enforcement of the style guide's other rules is not currently available.
