### ISSUE TITLE
Support for imported projects

### ISSUE THREAD

**Issue by rafal-wasowski** [looker-open-source/look-at-me-sideways#128]
I was struggling to understand why I can pass my matches in the rule sandbox but LAMS is failing to spot them and then it hit me:
lookml-parser very helpfully provides objects such as $name, $type, $file_type, $file_path etc. 

Since JsonPath doesn't have any functionality to match partial key values, those objects would be super useful to fully unblock the custom rules in LAMS.

Examples:
- apply rules to specific paths only (i.e. 'standard_layer' or 'raw_layer' in $file_path)
- apply rules to refinements only (i.e. $name starts with "+" character)

I understand this is not straightforward, LAMS would need to borrow the logic from lookml-parser to achieve this I think. However, if it would be possible to implement it in the future, that would be absolutely amazing.

**Comment by rafal-wasowski** [comment]
Actually, just to add to and expand on my previous point. The paths in JSONs produced by the lookml-parser seem to be completely different to the syntax suggested in https://looker-open-source.github.io/look-at-me-sideways/customizing-lams

For instance, JSONPath to a specific view (parsed JSON) might be $.file.view.'path_name'.view.'view_name', so neither $.files[*].view.* nor $.model.*.view.* will pick them up. 

Unless I'm missing something super obvious?

For reference, here's a truncated example of parsed JSON (using lookml-parser) from a live Looker project:

```
{
    "file": {
        "view": {
            "views/standard_layer/customers": {
                "include": "//hub/views/refined_views/customers.view.lkml",
                "view": {
                    "+customers": [
                        {
                            "$type": "view",
                            "$name": "+customers",
                            "sql_table_name": " `project.dataset.customers` ",
                            "fields_hidden_by_default": true,
                            "label": "Customer",
                            "dimension": {
                                "account_post_code_area": {
                                    "$type": "dimension",
                                    "$name": "account_post_code_area",
                                    "hidden": false,
                                    "map_layer_name": "uk_postcode_areas",
                                    "sql": "  REGEXP_EXTRACT(${account_post_code}, r'^\\D+') ",
                                    "description": "Letters of the first part of the postcode - this field can be used when plotting information on the map agaisnt the postcode areas where customers are located",
                                    "$view": "+customers"
                                }
                            }
                        }
                    ]
                },
                "$file_path": "views/standard_layer/customers.view.lkml",
                "$file_rel": "views/standard_layer/customers",
                "$file_name": "customers",
                "$file_type": "view"
            }
        }
    }
}
```

**Comment by fabio-looker** [comment]
Hi @rafal-wasowski 

I'll break down my answer in two parts, since the functionality will differ in v2 and v3 (currently available as a beta pre-release)

## LAMS v2

As suggested in the "About" tab of the LAMS Sandbox, in order to replicate the file representation that LAMS v2 receives, you should invoke node-lookml-parser with `--file-output=array` :
![image](https://user-images.githubusercontent.com/23034640/227837624-d227c409-d8b5-47bc-bd2a-95da77e5c222.png)

I'll admit this should probably be more visible...

## LAMS v3 (beta)

One of the complaints with working with files in custom rules under v2 is that the "array" representation made the matched path rather meaningless because the array index does not relate to any meaningful ordering of files, and users had to implement some dereferencing in their custom rules to find the relevant filename.

As a result, in v3, LAMS is being switched over to receiving the `--file-output=by-name` file representation, e.g. `$.file.["full/path.view"].(contents)`.

Also, I am tentatively reducing the number of duplicative $file_* metadata fields and just keeping $file_path (Feedback welcome here)

One more thing - since you are trying to work with refinements, I'd like to note that v3 introduces refinement support. While the contents under $.file.* will remain un-resolved, any contents under $.model.* will conveniently expose views & explores as refined/extended

**Comment by rafal-wasowski** [comment]
Hi @fabio-looker 

First and foremost, thank  you for this fantastic project, it's a life-saver! Secondly, great to hear that you're continuing development and that there's v3 around the corner.

As for the parser, this is exactly what I've been doing. The only difference being that I'm piping the output into a file, but that shouldn't impact anything, right?

`lookml-parser –file-output-array –whitespace=4 » output.json`

Is there perhaps a template available that shows what a workable json file should look like?

**Comment by rafal-wasowski** [comment]
Hey @fabio-looker,

A very quick update. Having fixed the unfortunate typo, the json output looks more akin to what I was expecting.

Interestingly enough, I still can't see any views under the 'model' node. I realise this is a more suitable question for the lookml-parser repo, but I wonder if it has anything to do with either the fact that all explores are based on refined views or that perhaps their names don't match the view names ('from' property used). Either way, I can't seem to be able to make use of paths '$.model.*.view.*' and derivatives.

Having said that, paths '$.files..view.*' work perfectly fine, which is all I needed!

**Comment by fabio-looker** [comment]
The views _objects_ should be available under the model key as long as: (A) one or more model files exist in your project, (B) the input argument, if changed from the default, includes one or more of those model files, and (C) the model file includes the files that declare the view objects (including the base object)

Other than that, I don't see why not. If it still eludes you, you can feel free to send me a copy of your LookML project to fabble@google.com and I can test it on my end

**Comment by rafal-wasowski** [comment]
Hi Fabio,

I wonder if the condition (C) is responsible for the fact that I can't see any view objects under the model key - all included views are refinements of base views in a remote project (they are not explicitly included in the model file).

I pinged you the copy of the project for review just in case. Thank you for taking your time to look into this!

**Comment by fabio-looker** [comment]
> base views in a remote project

This could very well be the issue. LAMS does not currently work with remote project imports.... however, it should be relatively easy to support, if the remote projects are pulled into a local file system folder before invoking LAMS. I will look into adding that within the upcoming 3.0 release which should be this month. Fair warning that I will have at best a very artificial test case, so bear with me for the initial release in case I will need to patch anything.

**Comment by rafal-wasowski** [comment]
Once again, thanks for looking into it. Like I said, not a major issue for me, since all the objects are still visible under the files key. Happy to test and give some feedback though should you need it 👍

**Comment by fabio-looker** [comment]
Hi @rafal-wasowski 

[v3](https://looker-open-source.github.io/look-at-me-sideways/release-notes/v3) is now generally available, and should let you lint over imported project contents (assuming you clone the project into the right location locally before invoking LAMS)

I'll close out this issue for now, but please let me know if you have any feedback about this!
