### ISSUE TITLE
3.0.0-beta.0 - K3 issues with refinements, and unable to exempt it

### ISSUE THREAD

**Issue by HermansSven** [looker-open-source/look-at-me-sideways#129]
I am using the following project-level rule exemption:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/55133906/231479342-11e5ee6b-fbc1-46f2-87d5-e5c4fbbc498d.png">

However, as you can see in my terminal, I'm still receiving errors for K3 errors.
If I put the rule exemption in the view file itself, then it works without issues.

**Comment by fabio-looker** [comment]
Hi @HermansSven 

Thanks for the bug report and for testing the beta!

This seems like it _should_ be caught by the test suite: https://github.com/looker-open-source/look-at-me-sideways/blob/fabble/v3-extends-refinements/__tests__/dummy-projects/15-global-exemptions/k1-4/index.test.js#L31

Can you confirm the following:

1. the command line arguments used 
2. the first couple messages output by LAMS which includes details on what it found in your manifest

**Comment by fabio-looker** [comment]
Looking at the test case further, I see that it might not catch the issue because the test case doesn't include a model and this rule was migrated to be model-based rather than file-based to take advantage of extension/refinement support.

I'll update the test cases later this week and let you know what I find!

**Comment by HermansSven** [comment]
Thanks for following up!
This is the command and output:
```
> lams --reporting=no --output=lines --date-output=none
Parsing project...
> Parsing done!
Checking rules... 
> E1
> E2
> F1
> F2
> F3
> F4
> K1
> K3
> K4
> T1
> T2-10
> W1
> Rules done!
        Rule    Location                                        Description
🛈      ....... project........................................ Project manifest settings read from manifest.lkml
🛈      ....... project........................................ Manifest properties: rule_exemptions
🛈      E1..... ............................................... Rule E1 summary: 1 matches, 0 matches exempt, and 0 errors
🛈      E2..... ............................................... Rule E2 summary: 1 matches, 0 matches exempt, and 0 errors
🛈      F1..... ............................................... Rule F1 summary: 20 matches, 0 matches exempt, and 0 errors
🛈      F2..... ............................................... Rule F2 summary: 20 matches, 0 matches exempt, and 0 errors
🛈      F3..... ............................................... Rule F3 summary: 1 matches, 0 matches exempt, and 0 errors
🛈      F4..... ............................................... Rule F4 summary: 17 matches, 0 matches exempt, and 0 errors
🛈      K1..... ............................................... Rule K1 summary: 3 matches, 0 matches exempt, and 0 errors
🛈      K3..... ............................................... Rule K3 summary: 3 matches, 0 matches exempt, and 1 errors
🛈      K4..... ............................................... Rule K4 summary: 3 matches, 0 matches exempt, and 0 errors
🛈      T1..... ............................................... Rule T1 summary: 1 matches, 0 matches exempt, and 0 errors
🛈      T3..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      T4..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      T5..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      T6..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      T7..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      T8..... ............................................... Evaluated 1 matches, with 0 exempt and 0 erroring
🛈      W1..... ............................................... Rule W1 summary: 203 matches, 0 matches exempt, and 0 errors
❌       K3..... m:wikipedia/v:wikipedia........................ View wikipedia contains dimensions declared before PK dimension(s), e.g. id
```
This is the manifest file:
```

#LAMS
#rule_exemptions: {
# K3: "Refinement file on top of auto_generated file"
#}

```

**Comment by HermansSven** [comment]
btw, the reason that I'm adding K3 as rule exemption is because I am using an auto-generated view and a refinement view on top of it. I have the primary_key on top in the refinement view, but it's not on top in the auto_generated view which is why it complains. Might be an interesting case to look at as well :)

**Comment by fabio-looker** [comment]
> I have the primary_key on top in the refinement view, but it's not on top in the auto_generated view which is why it complains. Might be an interesting case to look at as well :)

Good observation, I think K3 (which is about ordering of the syntax) didn't translate so naturally into refinements.

Perhaps it should stay as a "lexical"/file-based rule and only apply to declarations that do have any pk_ dimension? Happy to take suggestions!

**Comment by HermansSven** [comment]
Yep I think that makes sense! Then you know that if the primary key is not at the top of the file that it will be on top of another refinement file

**Comment by fabio-looker** [comment]
Pre-release [3.0.0-beta.1](https://www.npmjs.com/package/@looker/look-at-me-sideways/v/3.0.0-beta.1) should contain multiple fixes and an enhancement around this.

- Project exemptions at the project.manifest level are respected
- Going forward, all built-in rules are opt-in, so in most cases you can just omit the rule without any need for a project exemption
- If you do opt-in to K3, it now applies only to view files as declared, and in case they contain 0 pk_dimensions, K3 would not apply

Thank you for filing this bug, and in advance for letting me know if this resolves things for you!

**Comment by fabio-looker** [comment]
[v3](https://looker-open-source.github.io/look-at-me-sideways/release-notes/v3) is now generally available.

If you are still experiencing any issues, please let me know in a new comment and I'll re-open the issue

Thanks again for the bug report and continued feedback!
