### ISSUE TITLE
F3, ignore when measure is hidden in refinement (version 3.0.0-beta.0)

### ISSUE THREAD

**Issue by bendiktv2** [looker-open-source/look-at-me-sideways#131]
Hello, when using version 3.0.0-beta.0, we are still receiving F3-issues on autogenerated count-measures, that are hidden in refinement. 

We are getting autogenerated views by using Looker's "Create View From Table", and fetching all our tables from BigQuery, which auto-populates the dimensions with types and descriptions for us, and it also adds a default "count" measure, without any filters. We then refine the views, where we add primary-keys, hide unwanted dimensions/measures, and add new ones.
Since there is no way to **delete** the auto-generate measure (without editing the auto-generated file, which will be overwritten the next time it is auto-generated), we **hide** it. LAMS rule F4 ignores the hidden fields, but rule F3 does not ignore hidden measures.

Can F3 safely ignore all measures that are hidden, or are there some reasons that we are unaware of to still report F3-issues on hidden measures? Is there a way to **delete** a measure in a refined view?

**Comment by fabio-looker** [comment]
Hidden measures can still be surfaced, for example by users explicitly typing them into the URL, or by drill_fields.

Would it be reasonable to apply the LAMS extension in the refinement?

**Comment by bendiktv2** [comment]
Then I guess it would be reasonable to use exemptions, or create a custom rule that satisfies our use of hiding autogenerated count-measures.
