### ISSUE TITLE
Not able to add exemption for W1 (v3.0.0-beta.0)

### ISSUE THREAD

**Issue by bendiktv2** [looker-open-source/look-at-me-sideways#133]
Hello again,

I am unable to add an exemption for the W1 rule in v3 beta.
I tried to add the following comment to the `manifest.lkml` and to the model-file:
```LookML
# LAMS
# rule_exemptions: {
#  W1: "2023-05-03 - Other lint-issues are more important than whitespacing."
# }
```

The top output from running looks like:
```
        Rule    Location                                        Description
🛈       ....... project........................................ Project manifest settings read from manifest.lkml
🛈       ....... project........................................ Manifest properties: project_name, rule_exemptions, remote_dependency, constant, local_dependency
<snip>
🛈       W1..... ............................................... Rule W1 summary: 42589 matches, 248 matches exempt, and 1280 errors
```

And an example of a W1 issue:
```
❌      W1..... my_model/0/d:my_dim Expected inner indentation level: 2, found 3: ❌••••}
```

**Comment by fabio-looker** [comment]
Thanks for the report! I believe this is a duplicate of this more general issue: https://github.com/looker-open-source/look-at-me-sideways/issues/129

I'm working on fixing this, and will be publishing a new beta release soon, but will leave this ticket open to confirm resolution.

**Comment by fabio-looker** [comment]
Pre-release [3.0.0-beta.1](https://www.npmjs.com/package/@looker/look-at-me-sideways/v/3.0.0-beta.1) should contain fixes and an enhancement around this.

- Project exemptions at the project.manifest level should be respected
- Going forward, all built-in rules are opt-in, so in most cases you can just omit the rule without any need for a project exemption

Thank you for filing this bug, and in advance for letting me know if this resolves things for you!

**Comment by bendiktv2** [comment]
Thanks, 3.0.0-beta.1 changes to opt-in, and even opting in and then adding exemption seems to work correctly :)
