### ISSUE TITLE
Request to fix License name in package.json 

### ISSUE THREAD

**Issue by k7ragav** [looker-open-source/look-at-me-sideways#153]
Hi,

I'd like to propose to change the license from "Unlicensed" to "MIT" in the package.json file

Context:
I work for a financial institution where we adhere to stringent software usage policies. As part of our protocol, we rely exclusively on pre-vetted npm packages to ensure stability and security.

Even though there is a MIT license for this project, the "Unlicensed" mention here: https://www.npmjs.com/package/@looker/look-at-me-sideways is being a blocker for us. Our process scans through the license name in the npm package and since it is "Unlicensed", the package is not being greenlit. Therefore, changing the name in package.json could help us. 

Given the above concerns, I kindly request the consideration for changing the license name in the npm package. This change would greatly assist organizations like ours in maintaining a stable and secure software environment.

Thank you for your understanding and consideration.

Best regards,

Keshava Ragavendra

**Comment by fabio-looker** [comment]
Hi @k7ragav,

In https://github.com/looker-open-source/look-at-me-sideways/commit/fb94c57f02e9045b093a20d22d86be13d314b33e, I have updated the field in package.json, correctly renamed the LICENSE file, and updated the parser dependency to use the newly published parser version with the similar fix. These changes are published to NPM as 3.1.2

Thanks again for motivating me to getting around to getting this fixed, and let me know if you're still seeing any issues!
