### ISSUE TITLE
Missing expr_rule

### ISSUE THREAD

**Issue by Rkohn123** [looker-open-source/look-at-me-sideways#157]
Hello all, I have implemented all default rules in my manifest.lkml, 

#LAMS
#rule: K1{} 
#rule: K3{} 
#rule: K4{} 
#rule: K5{} 
#rule: K6{} 
#rule: F1{} 
#rule: F2{} 
#rule: F3{} 
#rule: F4{} 
#rule: F5{} 
#rule: F6{} 
#rule: E1{} 
#rule: E2{} 
#rule: E3{} 
#rule: E4{} 
#rule: E5{} 
#rule: E6{} 
#rule: E7{} 
#rule: W1{} 
#rule: T1{} 
#rule: T2.1{} 
#rule: T2.2{} 
#rule: T2.3{} 
#rule: T2.4{} 
#rule: T2.5{} 
#rule: T2.6{} 
#rule: T2.7{} 
#rule: T2.8{} 
#rule: T11{}
#rule: T12{}
#rule: T13{}
#rule: T14{}
#rule: T15{} 

But I have some errors, especially on these rules
❌  	E3.....	manifest/rule:E3...............................	Missing expr_rule in manifest/rule:E3
❌  	E4.....	manifest/rule:E4...............................	Missing expr_rule in manifest/rule:E4
❌  	E5.....	manifest/rule:E5...............................	Missing expr_rule in manifest/rule:E5
❌  	F5.....	manifest/rule:F5...............................	Missing expr_rule in manifest/rule:F5
❌  	F6.....	manifest/rule:F6...............................	Missing expr_rule in manifest/rule:F6
❌  	K5.....	manifest/rule:K5...............................	Missing expr_rule in manifest/rule:K5
❌  	K6.....	manifest/rule:K6...............................	Missing expr_rule in manifest/rule:K6
❌  	T11....	manifest/rule:T11..............................	Missing expr_rule in manifest/rule:T11
❌  	T12....	manifest/rule:T12..............................	Missing expr_rule in manifest/rule:T12
❌  	T13....	manifest/rule:T13..............................	Missing expr_rule in manifest/rule:T13
❌  	T14....	manifest/rule:T14..............................	Missing expr_rule in manifest/rule:T14
❌  	T15....	manifest/rule:T15..............................	Missing expr_rule in manifest/rule:T15
❌  	T2.1...	manifest/rule:T2.1.............................	Missing expr_rule in manifest/rule:T2.1
❌  	T2.2...	manifest/rule:T2.2.............................	Missing expr_rule in manifest/rule:T2.2
❌  	T2.3...	manifest/rule:T2.3.............................	Missing expr_rule in manifest/rule:T2.3
❌  	T2.4...	manifest/rule:T2.4.............................	Missing expr_rule in manifest/rule:T2.4
❌  	T2.5...	manifest/rule:T2.5.............................	Missing expr_rule in manifest/rule:T2.5
❌  	T2.6...	manifest/rule:T2.6.............................	Missing expr_rule in manifest/rule:T2.6
❌  	T2.7...	manifest/rule:T2.7.............................	Missing expr_rule in manifest/rule:T2.7
❌  	T2.8...	manifest/rule:T2.8.............................	Missing expr_rule in manifest/rule:T2.8

Do you know why ?

**Comment by fabio-looker** [comment]
Hi @Rkohn123 !

Yes, the rules for which you are seeing errors here are rules that do not exist in the linter. See the main readme for a list of all the implemented rules:

![image](https://github.com/looker-open-source/look-at-me-sideways/assets/23034640/86149b5c-7c60-4dde-a0a5-b68a17416d6c)

Also, note that in the style guide, rules which do not exist in the linter are marked with a  💬

Finally, all the T.x rules are just a subset of T2, you only need to opt-in to T2

I'll mark the issue as completed, but if you still have any questions, feel free to reply!
