### ISSUE TITLE
Adding a new rule on suggest_explore

### ISSUE THREAD

**Issue by Rkohn123** [looker-open-source/look-at-me-sideways#170]
Hello ! I would like to add a new rule about suggest_explore but it's a bit hard for me. I'd like to create a new rule that throws an error if it doesn't find a suggest_explore in the string dimensions for views starting with the name "lu_". 

So far I've done this and it doesn't work (I still need to add the constraint on views starting with "lu_"). What should I do? 

description: "Les dimensions de type string doivent contenir un suggest_explore"
match: "$.model.*.view.*.dimension[?(@.type==="string")]"
expr_rule: 
 ($if (=== ::match:suggest_explore undefined)
    ($concat "Type:Suggest Explore \`" ::match:$name "\` does not have a suggest explore")
  true
 )

**Comment by fabio-looker** [comment]
Hi @Rkohn123 - the condition operator in the JSONPath match expression is suited for simple equality comparisons, and beyond that, any conditions should be handled by the rule expression after matching, something like:

```
expr_rule:
($let view_name ($get path 3))
($if
  ($match "^lu_" view_name)
  ($if
    (=== ::match:suggest_explore undefined)
    ($concat "Type:Suggest Explore `" ::match:$name "` does not have a suggest explore")
    true
  )
  true
)
```

![image](https://github.com/looker-open-source/look-at-me-sideways/assets/23034640/e9dec983-a328-4ca9-82b1-8da434ca299f)

I'll mark the issue as closed, but feel free to respond if you still have any questions, and if so I'll respond here!

**Comment by Rkohn123** [comment]
Thank you ! 

It work but not as expected. 

My code look like this 

#rule: Suggest_explore {
#  description: "Les dimensions de type string doivent contenir un suggest_explore"
#  match: "$.model.*.view.*.dimension[?(@.type==='string')]"
#  expr_rule:
#   ($if
#    ($match "^lu_" view_name)
#    ($if
#      (=== ::match:suggest_explore undefined)
#      ($concat "Type:Suggest Explore `" ::match:$name "` does not have a suggest explore")
#      true
#     )
#     true
#   ) ;;
# }

But in my CI/CD :  Suggest	...............................................	Rule Suggest_explore summary: 374 matches, 0 matches exempt, and 0 errors 

It didn't find any errors even and in one of my view I have for example : 

  dimension: country {
    hidden: yes
    type: string
    description: "Identifiant du pays"
    map_layer_name: countries
    sql: ${TABLE}.country ;;
  }
  
  It should provide an error for this field for a suggest_explore, but it didn't :/ 

Thank you a lot fabio ! :)
