### ISSUE TITLE
How can you refer to two different paths in an expression?

### ISSUE THREAD

**Issue by BrunaBoaventura** [looker-open-source/look-at-me-sideways#24]
I am writing a few custom rules that fit our requirements and one of them needs to refer to two paths. I want to check if the type is yesno and if it is, then check if the dimension name ends with a _flag.
I tried changing the path inside the expression but that doesn't work either. Any tips on how to write this?

**Comment by fabio-looker** [comment]
Hmm, LAMS is using an open-source [JSONpath](https://www.npmjs.com/package/jsonpath) library.

It does let you define conditions, like so...

```
$.model.*.view.*.dimension.*[?(@.type=='yesno')]
```

However, the expressions you can use in these conditions are pretty limited, for security, so I don't think you can do pattern matching, like "ends in _flag"

However, you could do that inside of your expression, passing any field that does not end in "_flag":

```
($any
    ($not ($match ("_flag$", ::match:_dimension))
    (...expression that passes or fails _flag dimensions)
)
```
