### ISSUE TITLE
Share GitLab CI configuration

### ISSUE THREAD

**Issue by PieterjanCriel** [looker-open-source/look-at-me-sideways#25]
Sharing my Gitlab CI setup (which was a quick project);
Created a simple Dockerfile to wrap look-at-me-sideways

```bash
FROM alpine:edge

WORKDIR /opt/lams

RUN apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ upgrade && \
 apk --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ add \
 nodejs nodejs-npm

RUN  npm i -g @looker/look-at-me-sideways --unsafe-perm

CMD ["/bin/sh"]
```
This image is stored in the registry; (registry.example.com/look-at-me-sideways-bot)

Created a `gitlab-ci.yml` file in the LookML repo

```gitlab-ci
stages:
  - 👀 Look at me sideways

Lint:
  stage: 👀 Look at me sideways
  image:
    name: registry.example.com/look-at-me-sideways-bot
    entrypoint: [""]
  script:
  - lams --reporting=no --output-to-cli
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - issues.md
  when: on_success
  allow_failure: true
```

On every commit, lams will run an saves the `issues.md` in the Gitlab CI artifacts.

**Comment by fabio-looker** [comment]
Thanks so much for contributing this :) I'm out for Thanksgiving but will get it merged in next week!

**Comment by fabio-looker** [comment]
Sorry it took me a bit longer than expected! This is now available here and linked to from the main readme: https://looker-open-source.github.io/look-at-me-sideways/gitlab-ci

Thanks again!!

**Comment by mdmoniger** [comment]
Could you help me understand this? I think I'm missing something. I've added the above files to my gitlab repo, but LAMS still isn't working. What is the registry? I've tried changing that to the URL of the gitlab repo, but that doesn't work.

**Comment by mdmoniger** [comment]
@fabio-looker @PieterjanCriel Could you please help me out with implementing this? I've added the Dockerfile to the registry (my public Docker Hub), created the .yml file in my LookML repo, changed the URL to that of my Docker Hub repo, and populated the LAMS reporting arguments. But when I make a commit via gitlab or Looker, nothing happens. What am I missing? Thanks!

**Comment by fabio-looker** [comment]
Unfortunately, I have never used GitLab CI and won't be of too much help here. Perhaps GitLab's support might be able to quickly identify why nothing seems to be running upon commit.

**Comment by PieterjanCriel** [comment]
Hi @mdmoniger does this stage (👀 Look at me sideways) appear in the gitlab-ci pipeline (assuming that a commit triggers a pipeline)? If it does not appear there than the gitlab-ci file is not valid (you should have got a warning if so).

**Comment by mdmoniger** [comment]
@PieterjanCriel I do see it in the pipeline. I think I may be hosting it incorrectly or referencing the registry incorrectly.
I have these lines in the .yml file: 
```yaml
Lint:
  stage: 👀 Look at me sideways
  image:
    name: "https://hub.docker.com/repository/docker/mdmoniger/look-at-me-sideways/latest"
    entrypoint: [""]
```
And here is the error I'm getting:
![Screen Shot 2020-11-23 at 9 32 43 AM](https://user-images.githubusercontent.com/34489998/99988836-37758300-2d6f-11eb-99f2-8b5cbecc901e.png)
