### ISSUE TITLE
Wrong implementation of K1 rule

### ISSUE THREAD

**Issue by ms32035** [looker-open-source/look-at-me-sideways#30]
You're using naming convention to check both K1 and K2 at the same time, while K1 should be checked basing on if there's a dimension that has a primary key attribute set to yes

**Comment by fabio-looker** [comment]
Hi!

This is by design. If you're interested in checking for the existence of `primary_key: yes`, I could add an example of doing this via custom rules. 

However, these are the reasons I didn't do so in the default rules:
- functionally, `primary_key: yes` just enables symmetric aggregates, which I usually suggest avoiding if possible
- when there is more than one primary key column, the `pk{n}_` naming convention and the `primary_key:yes` attribute would disagree about which dimensions are the primary key dimensions

**Comment by jmak123** [comment]
@fabio-looker Can you give an example of how to check existence of primary_key?

**Comment by fabio-looker** [comment]
Hi @jmak123 - to make this kind of rule easier to implement in the expression-based custom rule language, I am going to add a few helper functions for looping through objects - https://github.com/looker-open-source/look-at-me-sideways/issues/45

My hope is to get these added this week

**Comment by jmak123** [comment]
@fabio-looker Thank you! Looking forward to it.

**Comment by fabio-looker** [comment]
Hi @jmak123 - I sat down to do this today, and realized I had already done it long ago... oops! So I went ahead and made the example you requested as a testcase:

https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/08-object-iteration-rules/manifest.lkml

**Comment by jmak123** [comment]
Thanks so much @fabio-looker !
One thing though, the custom rule that iterates over dimensions seems to have problems outputting error to CLI.
I get 
```
RangeError: Invalid array length
    at formatArray (util.js:696:18)
    at formatValue (util.js:578:18)
    at Object.inspect (util.js:293:10)
    at Console.dir (console.js:158:14)
    at module.exports (/usr/local/lib/node_modules/@looker/look-at-me-sideways/index.js:181:13)
    at <anonymous>
```

**Comment by ajbosco** [comment]
> Hi @jmak123 - I sat down to do this today, and realized I had already done it long ago... oops! So I went ahead and made the example you requested as a testcase:
> 
> https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/08-object-iteration-rules/manifest.lkml

@fabio-looker We're having an issue where this fails if there is a view (say an `extends`) with no dimensions. Is there a way to handle that in the current implementation?

**Comment by fabio-looker** [comment]
> > Hi @jmak123 - I sat down to do this today, and realized I had already done it long ago... oops! So I went ahead and made the example you requested as a testcase:
> > https://github.com/looker-open-source/look-at-me-sideways/blob/master/__tests__/dummy-projects/08-object-iteration-rules/manifest.lkml
> 
> @fabio-looker We're having an issue where this fails if there is a view (say an `extends`) with no dimensions. Is there a way to handle that in the current implementation?

The LookML parser that LAMS uses does not currently resolve extensions/refinements before LAMS checks its rules, so in general anything that is done via extends is not recognized correctly. As of right now, using an exemption is the only solution. I will try to look for opportunities to work on extensions support in the parser in the future, as this will solve not only this, but a broad set of issues.

**Comment by ajbosco** [comment]
> @ajbosco
> 
> 
> 
> The LookML parser that LAMS uses does not currently resolve extensions/refinements before LAMS checks its rules, so in general anything that is done via extends is not recognized correctly. As of right now, using an exemption is the only solution. I will try to look for opportunities to work on extensions support in the parser in the future, as this will solve not only this, but a broad set of issues.

Thanks that totally makes sense about extensions but what I'm trying to do is just get a rule that can iterate over Dimensions and won't throw a build error if none are present in a view.

**Comment by fabio-looker** [comment]
Hi @ajbosco - I missed this reply earlier, sorry about that. You can always put in a conditional to guard against empty objects. I made an example here:

https://github.com/looker-open-source/look-at-me-sideways/blob/shortcircuit-example/__tests__/dummy-projects/10-shortcircuit-custom-rule/manifest.lkml
