### ISSUE TITLE
Question about rule F3

### ISSUE THREAD

**Issue by adriantoman** [looker-open-source/look-at-me-sideways#31]
Hi

I have a question about the style rule F3. Is there any explanation of why this rule is valid? I have checked it in the latest version of Looker and it doesn't look like that looker is using COUNT(*) syntax anymore.

Is it possible that this rule is obsolete? or it is connected to specific database?

Thank you
Adrian

**Comment by fabio-looker** [comment]
Hi Adrian! You're the first person to bring it to my attention, but it looks like you may be right. I'll research this and confirm in more detail

**Comment by fabio-looker** [comment]
Actually, I have to immediately take it back. The model that I first thought to test on had some custom written SQL for all of its counts.

Upon looking at a plain `type: count` field, on a Redshift connection, on Looker 6.24, I am still seeing `COUNT(*)`.

Is it possible that you are looking at the count of a many-to-one joined table, where Looker has applied a distinct on the primary key?

**Comment by fabio-looker** [comment]
Closing this out for now due to lack of response. Let me know if you still need any help!
