### ISSUE TITLE
Disable date in issues.md

### ISSUE THREAD

**Issue by villoro** [looker-open-source/look-at-me-sideways#35]
We use LAMS with at some repositories where we use pull requests (PR). Each time we close a PR we get merge conflicts with the existing ones caused by the file `issues.md`.

The problem is that each branch is writting the line with the date and that causes the conflicts. The line is:
```html
<p style="text-align:right;color:#cccs">
Generated Mon, 22 Jun 2020 15:39:09 GMT
</p>
```

It is possible to configure it so that LAMS does not write the date on the `issues.md`? I think that the best solution will be to have a parameter to disable the date.

**Comment by fabio-looker** [comment]
Hi! There is no such option at the moment, but it seems like a very reasonable option to add (even if in some ideal world it would be even better to deliver messages via some other channel and not the repo itself)

If you submit a PR, I would merge it, if not I can probably add this option at some point in the next few weeks

The following place would need a conditional: https://github.com/looker-open-source/look-at-me-sideways/blob/master/lib/templates/issues.jst#L27

And the following call would need an argument passed: https://github.com/looker-open-source/look-at-me-sideways/blob/master/index.js#L207

**Comment by fabio-looker** [comment]
Ok, in theory this should be ready. Lemme know if you run into any issues.

Also, if you want, feel free to message me about how you are using LAMS and how you like the rules, I am always curious to know! fabio@looker.com

**Comment by villoro** [comment]
It works perfectly 😁 

Let me just think a little bit about it and I'll write you.
