### ISSUE TITLE
Lams could not be used, SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by alphacr** [looker-open-source/look-at-me-sideways#37]
Hi, is the library failing for anyone else?

This is my first time using it and I'm already running into problems when I'm trying to run it.

Commands i run:

> sudo npm install -g @looker/look-at-me-sideways
> lams

error message on lams command:

```
/usr/local/lib/node_modules/@looker/look-at-me-sideways/cli.js:22
                .map(([k, v])=>[k.replace(/[-_][a-zA-Z-0-9]/g, (s)=>s.slice(1).toUpperCase()), v])
                      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Seems that the latest deployment itself has a failing CI build, could that be reason why? https://github.com/looker-open-source/look-at-me-sideways/commit/77b2ba02fdaf8f2dd96479b59010129f25890dd4

**Comment by fabio-looker** [comment]
Hey! It sounds like your system probably has an older version of node installed. I would recommend probably installing Node 10 or 12, though LAMS will probably work with 8 as well. If that doesn't fix it for you, feel free to re-open
