### ISSUE TITLE
Rule F3 and drill_fields

### ISSUE THREAD

**Issue by joshuasimon-taulia** [looker-open-source/look-at-me-sideways#38]
Do i still need to specify a filter in the case of something like
```
  measure: count {
    type: count
    drill_fields: [detail*]
  }

  # ----- Sets of fields for drilling ------
  set: detail {
    fields: [
      pk1_app_foo_relation_id,
      bar_company_code_name,
      foo_detail_name,
      pt_current_term_name,
      company_name,
      bar_name,
      name,
      foo.count
    ]
  }
}
```

**Comment by fabio-looker** [comment]
Yes, in fact this case is pretty much the explicit reason that this rule exists. The thing that the filter fixes is so unintuitive that it may be months before you eventually encounter the logical error, and the rule helps prevent it.

The rationale that I wrote under the rule tries to explain it, and I've added some additional clarification here:

By default Looker will implement any non-filtered & non-distinct count field as a `COUNT(*)`. This can be incorrect depending on how your explore joins this view. And as the writer of this view, you can't predict how current or future explores will join this view.

Filtering "plain" counts on PK IS NOT NULL ensures correct counts in all of the following uses of the field: Counting just that table, counting that table when joined on as a one-to-one-or-zero table, counting hat table with symmetric aggregates when joined on as a many_to_one table, and counting that table in explores with join paths.

I'm leaving this issue as closed but can reopen if necessary, let me know!
