### ISSUE TITLE
Should this break rule F1?

### ISSUE THREAD

**Issue by joshuasimon-taulia** [looker-open-source/look-at-me-sideways#39]
We have a view from a derived table
```lookml
view: currency_selector {
  derived_table: {
    sql:
      SELECT 'USD' AS currency
      UNION ALL
      SELECT 'EUR' AS currency
      UNION ALL
      SELECT 'GBP' AS currency
      UNION ALL
      SELECT 'AUD' AS currency
      UNION ALL
      SELECT 'CAD' AS currency;;
  }

  dimension: currency {
    type: string
    hidden: yes
    sql: ${TABLE}.currency ;;
  }

  parameter: currency_selector {
    suggest_dimension: currency
  }


}
```
 which we are using to dynamically populate currency types and symbols in another view(s)
```lookml
view: payment_ledger {
...
  dimension: general_currency {
    type: number
    sql: CASE WHEN {% parameter currency_selector.currency_selector %} = 'EUR' THEN ${amount_eur}
              WHEN {% parameter currency_selector.currency_selector %} = 'USD' THEN ${amount_usd}
              WHEN {% parameter currency_selector.currency_selector %} = 'GBP' THEN ${amount_gbp}
         ELSE ${amount_usd}
         END;;
    html: {{ currency_symbol._value }}{{ rendered_value }} ;;
    value_format_name: decimal_2
  }

  dimension: currency_symbol{
    type: string
    hidden: yes
    sql: CASE
        WHEN {% parameter currency_selector.currency_selector %} = 'EUR' THEN '€'
        WHEN {% parameter currency_selector.currency_selector %} = 'GBP' THEN '£'
        WHEN {% parameter currency_selector.currency_selector %} = 'USD' THEN '$'
        END;;
  }

  measure: total_other_actual {
    sql:  ${general_currency} ;;
    type:  sum
    value_format_name: big_money
    filters: [currency: "-USD, -EUR, -GBP", ledger_entry_type_description: "Actual"]
    html: {{ currency_symbol._value }}{{ rendered_value }} ;;
  }
```
would this quality as a `tightly coupled view` per [F1](https://looker-open-source.github.io/look-at-me-sideways/rules.html#f1)? is there a better way to do this? thanks for the clarification on the last issue btw.

**Comment by fabio-looker** [comment]
Hi @joshuasimon-taulia , glad to help!

Yes, I would definitely describe these views as tightly coupled, because you would not expect the payment_ledger to work without the currency selector, and would always require them to be used together in an explore. Unfortunately, this is just a judgement call, not something LAMS could infer from the code, so an exemption would be good here.

**Comment by fabio-looker** [comment]
Also, as an aside, if you are not _intending_ to reuse the currency_selector view with multiple fact views, you can just put the currency selector parameter directly inside of the payment ledger, and use the `suggest_explore` parameter to simply pull the suggestions from another explore, which could be a more intuitive setup overall

**Comment by joshuasimon-taulia** [comment]
Looks like our looker project has been designed to use `sql: CASE WHEN {% parameter currency_selector.currency_selector %} =` in multiple views to keep things DRY. Is there any workaround I can do to get these to pass? If not I'll just disable F1 in our manifest.
