### ISSUE TITLE
Support for CircleCI

### ISSUE THREAD

**Issue by mprogano** [looker-open-source/look-at-me-sideways#40]
We just open sources our CircleCI build, while I'm not an engineer it might be worth someone who is adding it into the mix here.
https://github.com/renewdotcom/renew-looker-template/tree/master/.circleci

**Comment by fabio-looker** [comment]
Hi @mprogano , this is an awesome contribution, thanks! (I'll probably get around to incorporating this next week)

**Comment by mprogano** [comment]
amazing!

**Comment by fabio-looker** [comment]
Sorry for the overdue update - I've added a link to your template into our README dosc. Thanks again!! :)
