### ISSUE TITLE
Output errors to a file & provide a custom manifest.lkml

### ISSUE THREAD

**Issue by romitjain** [looker-open-source/look-at-me-sideways#41]
Hi Team,
Thanks for creating LAMS, it's a wonderful tool that we are planning to use. I had 2 suggestions:
1. Can we output the errors to a file? I know we can use `--output-to-cli` but that does not seem to output all the error, instead it caps out at around 300 errors and displays `xx` more errors at the end. Our use case is that we want to display all the errors at pipeline failures.
2.  Can we provide a `manifest.lkml` file that is not in the looker project repository? The use case is that we want to have a central `manifest.lkml` for all our Looker projects that define all our custom linting rules.
Let me know if we have alternatives for the above two.

Thanks

**Comment by fabio-looker** [comment]
1. The limit is unintentional and is seems to be the result of the internal logic of node's `console.log` for large arrays. It should be pretty easy to update this to a loop over the array around [here](https://github.com/looker-open-source/look-at-me-sideways/blob/b867c24eb499e50ff17684fa1ce08091c7ab9d96/index.js#L177). I'd probably add an argument value, like `ndjson` to the `output-to-cli` parameter to toggle this functionality so as to not require a major semver change for those who may be relying on this output being a JSON array

2. This sounds like a good idea. Where/how would it make sense to store/pass this file?

**Comment by romitjain** [comment]
@fabio-looker Thanks for the quick reply :)
Re: 2, we can pass it as an argument, something like: `--manifest <loc-to-manifest>`

**Comment by fabio-looker** [comment]
@romitjain - For concern #1, I added a feature in 1.5 where you can pass a numerical argument to `output-to-cli` that should override the default length for array output.

**Comment by romitjain** [comment]
Thanks @fabio-looker, that helps! :)

**Comment by fabio-looker** [comment]
Hi @romitjain 

You may want to review the v2 release. It includes a nicer-formatted output  mode and the ability to pass in manifest arguments via a command-line argument. It is not exactly a separate path, but in researching a similar use case, I think you can just pass in the glob argument such that it sources your manifest file from a path outside your current project.

https://looker-open-source.github.io/look-at-me-sideways/release-notes/v2

![new output](https://user-images.githubusercontent.com/23034640/155213617-54dc3c11-c4a2-4bf9-adea-2115c66a0611.png)
