### ISSUE TITLE
GitHub Action Update

### ISSUE THREAD

**Issue by ErikKBethke** [looker-open-source/look-at-me-sideways#42]
Hello,

As of 11/16/2020 GitHub disabled the use of set-env commands ([link](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)). This causes LAMS set up through GitHub actions to have issues running properly.

Documentation for LAMS GitHub Actions [here](https://github.com/looker-open-source/look-at-me-sideways/blob/master/docs/github-action.md)

This can be resolved here by updating:
`      run: lams --reporting=... || echo "::set-env name=ERROR::true"`
 
to 
`      run: lams --reporting=save-no || echo "ERROR=true" >> $GITHUB_ENV`

Documentation from GitHub for setting environment variables: [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)

**Comment by fabio-looker** [comment]
Hi @ErikKBethke - thanks for the detailed issue report. Since this is just a change to documentation, I was able to make it without much fuss! Thanks again :)
