### ISSUE TITLE
native Looker validator complains about manifest.lkml

### ISSUE THREAD

**Issue by sincraianul** [looker-open-source/look-at-me-sideways#48]
Looker doesn't seem to like the `manifest.lkml` file :(

![Screenshot 2021-04-05 at 16 11 19](https://user-images.githubusercontent.com/1500799/113577201-91ddf480-9629-11eb-8618-73b3db26dcf7.png)

```
name: "XXX"

rule: filter_one {
  description: "yadda yadda"
  match: "$.model.*.explore.*"
  expr_rule: (!== ::match:access_filter undefined) ;; # error is here
}
```

Is there any way around this?

**Comment by sincraianul** [comment]
If anybody else faces this issue. my solution was to rename the file in the repo to something like `manifest._lkml` so that the validator ignores it. Then during the CI workflow, I rename it back to `manifest.lkml`. 😄

**Comment by fabio-looker** [comment]
Hi @sincraianul - sorry, I was OOO last week!

Just FYI, the intended way to do this is that all declarations intended for LAMS are hidden behind a special #LAMS comment

So you would have a `manifest.lkml` file like:

```
# LAMS
# rule: filter_one {
#  description: "yadda yadda"
#  match: "$.model.*.explore.*"
#  expr_rule: (!== ::match:access_filter undefined) ;; # error is here
# }
```
