### ISSUE TITLE
Exemption for custom rules

### ISSUE THREAD

**Issue by ajbosco** [looker-open-source/look-at-me-sideways#50]
Is it possible to set granular exemptions for custom rules? I tried something like this, but it didn't seem to work:

```
    # LAMS
    # rule_exemptions: {
    #  my_custom_rule: "2018-11-12 - I can't use datagroups for this super special reason and Bob said it's ok"
    # }
```

**Comment by fabio-looker** [comment]
It should be... I'll double check this week

**Comment by fabio-looker** [comment]
Hi @ajbosco  - I tested this late last week, and you were right, there was not yet any support for exemption (granular or global) of custom rules.

I have added the ability to support granular exemptions in the `exempt-custom-rules` branch.

You can see a test for the functionality here: https://github.com/looker-open-source/look-at-me-sideways/tree/exempt-custom-rules/__tests__/dummy-projects/09-exempt-custom-rules

Would you like to review this before I publish the update to NPM?

**Comment by ajbosco** [comment]
@fabio-looker Awesome. Looks good to me!

**Comment by fabio-looker** [comment]
Thanks! The new feature is in version 1.6+ on npm
