### ISSUE TITLE
Rule Exceptions Syntax not working

### ISSUE THREAD

**Issue by Priyankavl** [looker-open-source/look-at-me-sideways#55]
I tried the global rule exception syntax in manifest file, But I still get errors related to those rules. Am I missing anything?

Tried below syntaxes:
1)
```
 # LAMS
# rule_exemptions: {
#  K4: "Rule not Required"
# }
 # LAMS
# rule_exemptions: {
#  F2: "Rule not Required"
# }
```
2)
```
# LAMS
# rule_exemptions: {
#  k4,F2,F3,T1,T2: "Rule not Required"
# }
```
Please help me implement these exemptions.

I am getting the below error

error: {
      toString: [Function: toString],
      message: 'Expected "#", "expr", "html", "sql", "}", [ \\t\\n\\r], or [\\-+_a-zA-Z0-9.] but "," found.',
      expected: [Array],
      found: '[',
      location: [Object],
      name: 'SyntaxError',
      context: ''
    },
    _file_path: 'manifest.lkml',
    _file_rel: '',
    _file_name: '',
    _file_type: 'manifest'
  },

**Comment by fabio-looker** [comment]
Hi, thanks again for the question!

I've taken the opportunity to update the relevant docs page with the example of the syntax for more than one exemption

https://github.com/looker-open-source/look-at-me-sideways/commit/f09db4e45ed9db32773d0276191a3425925b46e4
