### ISSUE TITLE
Introduce/Support Foreign Keys?

### ISSUE THREAD

**Issue by marcelolx** [looker-open-source/look-at-me-sideways#57]
We have multiple joins which use the PK field of a given view and the Foreign Key to generate the correct join but LAMS keep saying in those scenarios that no PKs dimensions used for a given view in a given join, an example is the following explore 

```
include: "/views/items.view"
include: "/views/organizations.view"
include: "/views/addresses.view"

explore: invoices {
  view_name: items

  join: organizations {
    type: inner
    relationship: one_to_one
    sql_on: ${organizations.pk1_organization_id} = ${items.organization_id};;
  }

  join: addresses {
    view_label: "Organization Address"
    type:  inner
    relationship: one_to_one
    sql_on: ${organizations.address_id} = ${addresses.pk1_address_id};;
  }
}
```

For those two joins, it says that for example in the addresses join we didn't use a PK for the `organizations` view but we don't want to use the PK in this case since we want to join using the `address_id` on the organization and not his Primary Key.

I think that this could be fixed if LAMS would support/introduce Foreign Key as it does with PrimaryKey (name convention?) and here https://github.com/looker-open-source/look-at-me-sideways/blob/master/rules/e2.js#L80 where it checks if the name matches the PK regex it could also check if not matches the PK regex check if it matches the Foreign Key regex.

---
Maybe we're missing something in our LookML files but as far as I could understand LAMS always expect an one_to_one join to be between two PKs instead of one PK and an FK.

**Comment by fabio-looker** [comment]
Hi @marcelolx 

Thanks for submitting the ticket! I would say this is an example of LAMS highlighting a valid error.

The issue is that you have declared the join as `one_to_one`, but since items.organization_id is a foreign key and not a primary key, the join should actually be `many_to_one`

If for some reason you want to force the join to be `one_to_one` without ensuring it's the case through the use of primary keys, you can add a rule exemption within the join.

I'll mark this ticket as closed for now, but feel free to respond and I'll review!

**Comment by marcelolx** [comment]
Oh my bad, thanks for pointing that out @fabio-looker! Feel free to close it.

**Comment by marcelolx** [comment]
@fabio-looker Just one question, shouldn't this work for an `one_to_many` join as well?

**Comment by fabio-looker** [comment]
@marcelolx 

> Just one question, shouldn't this work for an `one_to_many` join as well?

Whichever side of the join that you want to claim as having cardinality "one" (could be either side or both) should be enforced by applying an equality constraint to its primary key(s)

- one_to_one: needs to have primary key constraints applied to both tables
- one_to_many: needs to have a primary key constraint applied to the "left" / "existing" table
- many_to_one: needs to have a primary key constraint applied to the "right" / "joined" table

**Comment by marcelolx** [comment]
Thanks @fabio-looker! Got it working here.
