### ISSUE TITLE
Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by abuckenheimer** [looker-open-source/look-at-me-sideways#60]
```
TypeError: Cannot read properties of undefined (reading 'url')
    at /c/dev/work/node/node-v16.13.2-linux-x64/lib/node_modules/@looker/look-at-me-sideways/rules/f1.js:44:59
    at Array.map (<anonymous>)
    at module.exports (/c/dev/work/node/node-v16.13.2-linux-x64/lib/node_modules/@looker/look-at-me-sideways/rules/f1.js:44:46)
    at module.exports (/c/dev/work/node/node-v16.13.2-linux-x64/lib/node_modules/@looker/look-at-me-sideways/index.js:131:26)
    at async /c/dev/work/node/node-v16.13.2-linux-x64/lib/node_modules/@looker/look-at-me-sideways/cli.js:28:2
```
Running into an issue when lams tries to parse a dimensions link property. Specifically
```
dimension: key {
    label: "Key"
    #group_label: "Jira"
    type: string
    sql: ${TABLE}.key ;;
    link: {
      url: "http://@{COMPANY_DOMAIN_JIRA}.atlassian.net/browse/{{ value }}"
      label: "View in Jira"
    }
  }
  ```
  If I comment this out lams runs fine.

**Comment by fabio-looker** [comment]
Hi @abuckenheimer - Unfortunately there was a change in how the lookml parser handles unnamed objects like `link` that was not caught by any existing test. This was already reported in https://github.com/looker-open-source/look-at-me-sideways/issues/58 and I am hoping to address it shortly. In the meantime, I am recommending that affected projects peg their lams dependency to v1. I'll close this as a duplicate, but thank you for submitting your sample code.
