### ISSUE TITLE
K1: Primary Key regex does not allow pk_{name}

### ISSUE THREAD

**Issue by ptsullivan** [looker-open-source/look-at-me-sideways#63]
The regex matches `1pk_id` or `pk1_id`, but not `pk_id` whereas the style guide says "n ... may be omitted if it is 1, and key_name is any descriptive name."

https://github.com/looker-open-source/look-at-me-sideways/blob/f09db4e45ed9db32773d0276191a3425925b46e4/rules/k1-2-3-4.js#L25

I suggest using `^([0-9]+pk|pk[0-9]+|pk)_([a-z0-9A-Z_]+)$`

**Comment by fabio-looker** [comment]
Fixed in 2.1.3
